{
 "title": "Azure MongoDB",
 "tags": [
  "azure",
  "templates"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "ResourceGroup", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "label": "Resource Name",
    "query": "ResourceNames($ResourceGroup,Microsoft.DocumentDB/databaseAccounts)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Document Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "DocumentCount",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ]
     }
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "AvailableStorage",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ]
     }
    }
   ]
  },
  {
   "title": "Document Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "DocumentQuota",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests / Command",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "alias": "{{dimensionvalue}}",
      "dimension": "CommandName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests / Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "alias": "{{dimensionvalue}}",
      "dimension": "DatabaseName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests / Collection Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "alias": "{{dimensionvalue}}",
      "dimension": "CollectionName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests / Error Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "alias": "{{dimensionvalue}}",
      "dimension": "ErrorCode",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequests",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests charge / Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "dimension": "DatabaseName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequestCharge",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests charge / Collection Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "dimension": "CollectionName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequestCharge",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Requests charge / Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "dimension": "Region",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "CommandName", "value": "CommandName" },
       { "text": "ErrorCode", "value": "ErrorCode" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "MongoRequestCharge",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}